package:  url_path_rewrite
version:  '2.3'
author:   Wolfgang Busch
supportpage: redaxo.org/support/community/

page:
    title: 'translate:url_path_rewrite'
    perm:  admin[]
    icon:  rex-icon fa-area-chart
    subpages:
        introduction: { title: 'translate:introduction' }
        rewrite:      { title: 'translate:rewrite' }
        description:  { title: 'translate:description' }
        handling:     { title: 'translate:handling' }
        config:       { title: 'translate:config' }

requires:
    redaxo: ^5.3.0
