package: url_path_rewrite
version: '1.0.2'
author: 'Wolfgang Busch'
supportpage: redaxo.org/forum/

page:
    title: 'translate:url_path_rewrite'
    perm: url_path_rewrite[]
    subpages:
        introduction: { title: 'translate:introduction' }
        description:  { title: 'translate:description' }
        htaccess:     { title: 'translate:htaccess' }
        handling:     { title: 'translate:handling' }
        config:       { title: 'translate:config' }

requires:
    redaxo: ^5.1.0
